(function(){
var g=false,i=null,l=true,aa=(new Date).getTime();var ba={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_tag_js_version:"gut",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},ca={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",
google_analytics_uacct:"ga_wpids",google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",
google_rt:"rt",google_skip:"skip"};document.URL&&(document.URL.indexOf("?google_debug")>0||document.URL.indexOf("&google_debug")>0);function n(){this.I=this.wb();this.Ta=g;if(!this.I)this.Ta=this.ab()}n.prototype.ha="__gads=";n.prototype.S="GoogleAdServingTest=";n.prototype.gb=function(){return this.I};n.prototype.setCookieInfo=function(a){this.B=a._cookies_[0];if(this.B!=i){this.I=this.B._value_;this.Fb()}};n.prototype.db=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
n.prototype.cb=function(a){if(!(this.I!=i||!this.Ta)){var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+da(a)+"&domain="+da(c);document.write("<"+b+' src="'+d+'"></'+b+">")}};n.prototype.ab=function(){document.cookie=this.S+"Good";var a=this.Ea(this.S),b=a=="Good";if(b){var c=this.db(-1);document.cookie=this.S+"; expires="+c.toGMTString()}return b};n.prototype.wb=function(){var a=this.Ea(this.ha);return a};
n.prototype.Ea=function(a){var b=document.cookie,c=b.indexOf(a),d=i;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};n.prototype.Fb=function(){if(!(this.B==i))if(!(this.I==i)){var a=new Date;a.setTime(1000*this.B._expires_);var b=this.B._domain_,c=this.ha+this.I+"; expires="+a.toGMTString()+"; path="+this.B._path_+"; domain=."+b;document.cookie=c}};function ea(a,b){var c;return a?(c=parseFloat(a))?c:b:b}
function fa(a,b){if(a=="true")return l;if(a=="false")return g;return b}
function ga(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=i}return b.toString()}else if(ha()){var c=i;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");
b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=i){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"};var ia=ia||{},r=this,ka=function(a,b,c){var d=a.split("."),e=c||r,f;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);while(d.length&&(f=d.shift()))if(!d.length&&ja(b))e[f]=b;else e=e[f]?e[f]:(e[f]={})},la=function(a,b){var c=a.split("."),d=b||r;for(var e;e=c.shift();)if(d[e])d=d[e];else return i;return d},s=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!ma(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b},oa=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return l;return g};if(Object.prototype.propertyIsEnumerable)var ma=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):oa(a,b)};else ma=oa;var ja=function(a){return typeof a!="undefined"};
var pa=function(a){return s(a)=="function"},qa=function(a){var b=s(a);return b=="object"||b=="array"||b=="function"},ta=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(ra)){var b=a[ra];if(b)return b}a[ra]||(a[ra]=++sa);return a[ra]},ra="closure_hashCode_",sa=0,ua=function(a){var b=s(a);if(b=="object"||b=="array"){if(a.clone)return a.clone.call(a);var c=b=="array"?[]:{};for(var d in a)c[d]=ua(a[d]);return c}return a},t=function(a,b){var c=a.Gb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,
2);c&&d.unshift.apply(d,c);c=d}b=a.Ib||b;a=a.Hb||a;var e,f=b||r;e=c?function(){var h=Array.prototype.slice.call(arguments);h.unshift.apply(h,c);return a.apply(f,h)}:function(){return a.apply(f,arguments)};e.Gb=c;e.Ib=b;e.Hb=a;return e},va=Date.now||function(){return(new Date).getTime()},wa=function(a,b,c){ka(a,b,c)},u=function(a,b){function c(){}c.prototype=b.prototype;a.o=b.prototype;a.prototype=new c;a.prototype.constructor=a};var xa=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==i?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},ya=function(a,b){var c=xa(a,b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};var za=function(a,b){this.x=ja(a)?a:0;this.y=ja(b)?b:0};za.prototype.clone=function(){return new za(this.x,this.y)};za.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var v=function(a,b){this.width=a;this.height=b};v.prototype.clone=function(){return new v(this.width,this.height)};v.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};v.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};v.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
v.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};v.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Aa=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ba=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a};
var Da=function(a,b){var c=0,d=Aa(String(a)).split("."),e=Aa(String(b)).split("."),f=Math.max(d.length,e.length);for(var h=0;c==0&&h<f;h++){var j=d[h]||"",k=e[h]||"",m=new RegExp("(\\d*)(\\D*)","g"),o=new RegExp("(\\d*)(\\D*)","g");do{var p=m.exec(j)||["","",""],q=o.exec(k)||["","",""];if(p[0].length==0&&q[0].length==0)break;var J=p[1].length==0?0:parseInt(p[1],10),N=q[1].length==0?0:parseInt(q[1],10);c=Ca(J,N)||Ca(p[2].length==0,q[2].length==0)||Ca(p[2],q[2])}while(c==0)}return c},Ca=function(a,
b){if(a<b)return-1;else if(a>b)return 1;return 0};var Ea,Fa,Ga,Ha,Ia,Ja,Ka,La,Ma,Na=function(){return r.navigator?r.navigator.userAgent:i};var Oa=function(){Ja=Ia=Ha=Ga=Fa=Ea=g;var a;if(a=Na()){var b=r.navigator;Ea=a.indexOf("Opera")==0;Fa=!Ea&&a.indexOf("MSIE")!=-1;Ha=(Ga=!Ea&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Ja=(Ia=!Ea&&!Ga&&b.product=="Gecko")&&b.vendor=="Camino"}};Oa();
var Pa=Ea,w=Fa,Qa=Ia,Ra=Ja,x=Ga,Sa=Ha,Ta=function(){var a=r.navigator;return a&&a.platform||""},Ua=Ta(),Va=function(){Ka=Ua.indexOf("Mac")!=-1;La=Ua.indexOf("Win")!=-1;Ma=Ua.indexOf("Linux")!=-1};Va();var Wa=Ka,Xa=La,Ya=Ma,Za=function(){var a="",b;if(Pa&&r.opera){var c=r.opera.version;a=typeof c=="function"?c():c}else{if(Qa)b=/rv\:([^\);]+)(\)|;)/;else if(w)b=/MSIE\s+([^\);]+)(\)|;)/;else if(x)b=/WebKit\/(\S+)/;if(b){var d=b.exec(Na());a=d?d[1]:""}}return a},$a=Za();
var y=function(a){return Da($a,a)>=0};var ab;var cb=function(a){return a?new z(bb(a)):ab||(ab=new z)};var db=function(a){return typeof a=="string"?document.getElementById(a):a},ib=db,jb=function(a){var b=a||r||window,c=b.document;if(x&&!y("500")&&!Sa){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new v(b.innerWidth,d)}var f=cb(c),h=f.Y()&&(!Pa||Pa&&y("9.50"))?c.documentElement:c.body;return new v(h.clientWidth,h.clientHeight)};
var kb=function(a,b){a.appendChild(b)},lb=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):i},mb=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)},nb=x&&Da($a,"521")<=0,ob=function(a,b){if(typeof a.contains!="undefined"&&!nb&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},bb=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},z=
function(a){this.C=a||r.document||document};z.prototype.va=function(){return this.C};z.prototype.xa=function(a){return typeof a=="string"?this.C.getElementById(a):a};z.prototype.createElement=function(a){return this.C.createElement(a)};z.prototype.createTextNode=function(a){return this.C.createTextNode(a)};
z.prototype.Y=function(){var a=this.C;if(a.compatMode)return a.compatMode=="CSS1Compat";if(x){var b=a.createElement("div");b.style.cssText="position:absolute;width:0;height:0;width:1";var c=b.style.width=="1px"?"BackCompat":"CSS1Compat";return(a.compatMode=c)=="CSS1Compat"}return g};z.prototype.wa=function(){var a=this.C,b,c;if(!x&&this.Y()){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new za(b,c)};z.prototype.appendChild=kb;
z.prototype.removeNode=lb;z.prototype.replaceNode=mb;z.prototype.contains=ob;var pb,qb=function(a,b){var c=bb(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return i};
var rb=function(a){return qb(a,"position")||(a.currentStyle?a.currentStyle.position:i)||a.style.position},sb=function(a){var b;b=a?a.nodeType==9?a:bb(a):document;if(w&&!cb(b).Y())return b.body;return b.documentElement},tb=function(a){var b=a.getBoundingClientRect();if(w){var c=a.ownerDocument;b.left-=c.documentElement.clientLeft+c.body.clientLeft;b.top-=c.documentElement.clientTop+c.body.clientTop}return b},ub=function(a){var b=bb(a),c=Qa&&b.getBoxObjectFor&&rb(a)=="absolute"&&(a.style.top==""||a.style.left==
"");if(typeof pb=="undefined")pb=Ra&&!y("1.8.0.11");var d=new za(0,0),e=sb(b);if(a==e)return d;var f=i,h;if(a.getBoundingClientRect&&!c){h=tb(a);var j=cb(b).wa();d.x=h.left+j.x;d.y=h.top+j.y}else if(b.getBoxObjectFor&&!c&&!pb){h=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=h.screenX-k.screenX;d.y=h.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(f!=a){d.x+=f.clientLeft||0;d.y+=f.clientTop||0}if(x&&rb(f)=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;break}f=f.offsetParent}while(f&&
f!=a);if(Pa||x&&rb(a)=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!Pa||f.tagName!="TR")d.y-=f.scrollTop;f=f.offsetParent}}if(Qa&&a.getBoundingClientRect){var m=rb(a);if(m=="static"||m=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},vb=function(a){var b=new za;if(a.nodeType==1)if(a.getBoundingClientRect){var c=tb(a);b.x=c.left;b.y=c.top}else{var d=cb(a).wa(),e=ub(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b},wb=
function(a){var b=bb(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=qb(a,"fontFamily")||(a.currentStyle?a.currentStyle.fontFamily:i)||a.style.fontFamily;if(Pa&&Ya)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Ba(c,"\"'")};var xb=document,A=navigator,B=window;
function yb(){var a=xb.cookie,b=Math.round((new Date).getTime()/1000),c=B.google_analytics_domain_name,d=typeof c=="undefined"?zb("auto"):zb(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,h=a.indexOf("__utmc="+d)>-1,j,k={};if(e){j=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&h?j[3]+"":B&&B.gaGlobal&&B.gaGlobal.sid?B.gaGlobal.sid:b+"";k.vid=j[0]+"."+j[1];k.from_cookie=l}else{k.sid=B&&B.gaGlobal&&B.gaGlobal.sid?B.gaGlobal.sid:b+"";k.vid=B&&B.gaGlobal&&B.gaGlobal.vid?
B.gaGlobal.vid:(Ab()^Bb()&2147483647)+"."+b;k.from_cookie=g}k.dh=d;k.hid=B&&B.gaGlobal&&B.gaGlobal.hid?B.gaGlobal.hid:Ab();return B.gaGlobal=k}function Ab(){return Math.round(Math.random()*2147483647)}
function Bb(){var a=xb.cookie?xb.cookie:"",b=B.history.length,c,d,e=[A.appName,A.version,A.language?A.language:A.browserLanguage,A.platform,A.userAgent,A.javaEnabled()?1:0].join("");if(B.screen)e+=B.screen.width+"x"+B.screen.height+B.screen.colorDepth;else if(B.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=xb.referrer?xb.referrer:"";c=e.length;while(b>0)e+=b--^c++;return Cb(e)}
function Cb(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function zb(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=xb.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return Cb(a.toLowerCase())};var C=function(){};C.prototype.ua=g;C.prototype.dispose=function(){if(!this.ua){this.ua=l;this.b()}};C.prototype.b=function(){};var Db=function(a){if(/^\s*$/.test(a))return g;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},Eb=function(a){String(a);if(Db(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var D=function(){};D.prototype.serialize=function(a){var b=[];this.fa(a,b);return b.join("")};
D.prototype.fa=function(a,b){switch(typeof a){case "string":this.Ha(a,b);break;case "number":this.Cb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==i){b.push("null");break}if(s(a)=="array"){this.Bb(a,b);break}this.Db(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};
var Fb={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},Gb=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x80-\uffff]/g:/[\\\"\x00-\x1f\x80-\xff]/g;D.prototype.Ha=function(a,b){b.push('"',a.replace(Gb,function(c){if(c in Fb)return Fb[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return Fb[c]=e+d.toString(16)}),'"')};D.prototype.Cb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};
D.prototype.Bb=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.fa(a[e],b);d=","}b.push("]")};D.prototype.Db=function(a,b){b.push("{");var c="";for(var d in a)if(a.hasOwnProperty(d)){var e=a[d];if(typeof e!="function"){b.push(c);this.Ha(d,b);b.push(":");this.fa(e,b);c=","}}b.push("}")};var E="SETUP_ACK",F={},Ib=function(a,b){var c=b||Hb,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Hb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var G=function(){};u(G,C);G.prototype.f=0;var H=function(a){this.a=a;this.Q=[];this.Nb=t(this.Za,this)};u(H,G);H.prototype.f=2;H.prototype.ba=g;H.prototype.Eb=0;H.prototype.connect=function(){if(this.a.r()==0){this.l=this.a.s;this.l.XPC_toOuter=t(this.ya,this)}else this.la()};
H.prototype.la=function(){var a=l;try{if(!this.l)this.l=window.frameElement;if(this.l&&this.l.XPC_toOuter){this.Ca=this.l.XPC_toOuter;this.l.XPC_toOuter.XPC_toInner=t(this.ya,this);a=g;this.send("tp",E);this.a.m()}}catch(b){}if(a){if(!this.Ma)this.Ma=t(this.la,this);window.setTimeout(this.Ma,100)}};H.prototype.H=function(a){if(this.a.r()==0&&!this.a.g()&&a==E){this.Ca=this.l.XPC_toOuter.XPC_toInner;this.a.m()}else throw Error("Got unexpected transport message.");};
H.prototype.ya=function(a,b){if(!this.ba&&this.Q.length==0)this.a.j(a,b);else{this.Q.push({serviceName:a,payload:b});if(this.Q.length==1)this.Eb=window.setTimeout(this.Nb,1)}};H.prototype.Za=function(){while(this.Q.length){var a=this.Q.shift();this.a.j(a.serviceName,a.payload)}};H.prototype.send=function(a,b){this.ba=l;this.Ca(a,b);this.ba=g};H.prototype.b=function(){H.o.b.call(this);this.l=this.Ca=i};var I=function(a){this.a=a;this.R=this.a.c.ppu;this.Pb=this.a.c.lpu;this.da=[]},Jb,Kb;u(I,G);I.prototype.f=4;I.prototype.ea=0;I.prototype.v=g;I.prototype.O=g;var Lb="googlexpc";I.prototype.M=function(){return Lb+"_"+this.a.name+"_msg"};I.prototype.L=function(){return Lb+"_"+this.a.name+"_ack"};I.prototype.connect=function(){if(!this.O){this.Sa();this.O=l}this.Oa()};I.prototype.Sa=function(){var a=this.M();this.D=this.V(a);this.Aa=window.frames[a];a=this.L();this.w=this.V(a);this.ia=window.frames[a]};
I.prototype.V=function(a){var b=document.createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.R+"#INITIAL";document.body.appendChild(b);return b};I.prototype.mb=function(){this.a.name=Ib(10);this.ra();this.O=g;this.Rb=this.V(Lb+"_reconnect_"+this.a.name)};
I.prototype.rb=function(){var a=this.a.h.frames,b=a.length;for(var c=0;c<b;c++){var d;try{if(a[c]&&a[c].name)d=a[c].name}catch(e){}if(!!d){var f=d.split("_");if(f.length==3&&f[0]==Lb&&f[1]=="reconnect"){this.a.name=f[2];this.ra();this.O=g;break}}}};I.prototype.ra=function(){if(this.D){this.D.parentNode.removeChild(this.D);this.Aa=this.D=i}if(this.w){this.w.parentNode.removeChild(this.w);this.ia=this.w=i}};
I.prototype.Oa=function(){if(this.za(this.M())&&this.za(this.L())){this.ob=new Mb(this,this.a.h.frames[this.M()],t(this.ub,this));this.La=new Mb(this,this.a.h.frames[this.L()],t(this.tb,this));this.oa()}else{if(this.a.r()==1&&!this.Rb)this.mb();else this.a.r()==0&&this.rb();window.setTimeout(t(this.connect,this),100)}};I.prototype.za=function(a){try{var b=this.a.h.frames[a];if(!b||b.location.href.indexOf(this.Pb)!=0)return g}catch(c){return g}return l};
I.prototype.oa=function(){var a=this.a.h.frames;if(a[this.L()]&&a[this.M()]){this.pb=new Nb(this.R,this.Aa);this.T=new Nb(this.R,this.ia);window.setTimeout(t(function(){this.pb.send("SETUP");this.v=this.Ub=l},this),100)}else{if(!this.Pa)this.Pa=t(this.oa,this);window.setTimeout(this.Pa,100)}};I.prototype.na=function(){if(this.Ab&&this.Qb){this.a.m();if(this.K){for(var a=0,b;a<this.K.length;a++){b=this.K[a];this.a.j(b.service,b.payload)}delete this.K}}};
I.prototype.ub=function(a){if(a=="SETUP"){if(!!this.T){this.T.send(E);this.Ab=l;this.na()}}else if(this.a.g()||this.Ab){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.T.send("ACK:"+e);this.sa(d)}else{var e=c.substring(0,b);this.T.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.Da=[];this.Da.push(d);if(f[0]==f[1]){this.sa(this.Da.join(""));delete this.Da}}}};
I.prototype.tb=function(a){if(a==E){this.v=g;this.Qb=l;this.na()}else if(this.a.g())if(!!this.v){var b=parseInt(a.split(":")[1],10);if(b==this.ea){this.v=g;this.Ga()}}};I.prototype.Ga=function(){if(!(this.v||!this.da.length)){var a=this.da.shift();++this.ea;this.pb.send(this.ea+a);this.v=l}};I.prototype.sa=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);this.a.g()?this.a.j(c,d):(this.K||(this.K=[])).push({service:c,payload:d})};I.prototype.J=3800;
I.prototype.send=function(a,b){var c=a+":"+b;if(!w||b.length<=this.J)this.da.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.J),f=0,h=1;while(f<d){this.da.push(","+h+"/"+e+"|"+c.substr(f,this.J));h++;f+=this.J}}this.Ga()};I.prototype.b=function(){I.o.b.call(this);var a=Ob;ya(a,this.ob);ya(a,this.La);this.ob=this.La=i;lb(this.D);lb(this.w);this.Aa=this.ia=this.D=this.w=i};
var Ob=[],Qb=function(){var a=g;try{for(var b=0,c=Ob.length;b<c;b++)a=a||Ob[b].receive()}catch(d){Ob[b].d.a.qb();if(!Ob.length)return}var e=va();if(a)Jb=e;var f=e-Jb<1000?10:100;Kb=window.setTimeout(Pb,f)},Pb=t(Qb,I),Rb=function(){Jb=va();Kb&&window.clearTimeout(Kb);Kb=window.setTimeout(Pb,10)},Nb=function(a,b){this.R=a;this.zb=b;this.qa=0};Nb.prototype.send=function(a){this.qa=++this.qa%2;var b=this.R+"#"+this.qa+encodeURIComponent(a);try{if(x)this.zb.location.href=b;else this.zb.location.replace(b)}catch(c){}Rb()};
var Mb=function(a,b,c){this.d=a;this.vb=b;this.Jb=c;this.Xa=this.vb.location.href.split("#")[0]+"#INITIAL";Ob.push(this);Rb()};Mb.prototype.receive=function(){var a=this.vb.location.href;if(a!=this.Xa){this.Xa=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.Jb(decodeURIComponent(b))}return l}else return g};var K=function(a,b){C.call(this);this.nb=b;this.q=[];this.Va(a)};u(K,C);K.prototype.W=i;K.prototype.X=i;K.prototype.G=function(a){this.W=a};K.prototype.Ja=function(a){this.X=a};K.prototype.k=function(){if(this.q.length)return this.q.pop();return this.pa()};K.prototype.u=function(a){this.q.length<this.nb?this.q.push(a):this.ta(a)};K.prototype.Va=function(a){if(a>this.nb)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.q.push(this.pa())};
K.prototype.pa=function(){return this.W?this.W():{}};K.prototype.ta=function(a){if(this.X)this.X(a);else if(pa(a.dispose))a.dispose();else for(var b in a)delete a[b]};K.prototype.b=function(){K.o.b.call(this);var a=this.q;while(a.length)this.ta(a.pop());delete this.q};var L=function(a,b){this.type=a;this.currentTarget=this.target=b};u(L,C);L.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};L.prototype.F=g;L.prototype.ca=l;L.prototype.stopPropagation=function(){this.F=l};L.prototype.preventDefault=function(){this.ca=g};var M=function(a,b){a&&this.init(a,b)};u(M,L);M.prototype.type=i;M.prototype.target=i;M.prototype.relatedTarget=i;M.prototype.offsetX=0;M.prototype.offsetY=0;M.prototype.clientX=0;M.prototype.clientY=0;M.prototype.screenX=0;M.prototype.screenY=0;M.prototype.button=0;M.prototype.keyCode=0;M.prototype.charCode=0;M.prototype.ctrlKey=g;M.prototype.altKey=g;M.prototype.shiftKey=g;M.prototype.metaKey=g;M.prototype.i=i;
M.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:i;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.i=a;delete this.ca;delete this.F};M.prototype.stopPropagation=function(){this.F=l;if(this.i.stopPropagation)this.i.stopPropagation();else this.i.cancelBubble=l};
M.prototype.preventDefault=function(){this.ca=g;if(this.i.preventDefault)this.i.preventDefault();else{this.i.returnValue=g;try{this.i.keyCode=-1}catch(a){}}};M.prototype.eb=function(){return this.i};M.prototype.b=function(){M.o.b.call(this);this.i=i};var O=function(){},Sb=0;O.prototype.$=i;O.prototype.listener=i;O.prototype.proxy=i;O.prototype.src=i;O.prototype.type=i;O.prototype.capture=i;O.prototype.handler=i;O.prototype.key=0;O.prototype.removed=g;O.prototype.ma=g;O.prototype.init=function(a,b,c,d,e,f){if(pa(a))this.$=l;else if(a&&a.handleEvent&&pa(a.handleEvent))this.$=g;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.ma=g;this.key=++Sb;this.removed=g};
O.prototype.handleEvent=function(a){if(this.$)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var Tb={},P={},Ub={},Vb=new K(0,600);Vb.G(function(){return{p:0}});Vb.Ja(function(a){a.p=0});var Q=new K(0,600);Q.G(function(){return[]});Q.Ja(function(a){a.length=0;delete a.P;delete a.Ba});var Wb=new K(0,600);Wb.G(function(){var a=function(b){return Xb.call(a.src,a.key,b)};return a});var Yb=function(){return new O},Zb=new K(0,600);Zb.G(Yb);
var $b=function(){return new M},cc=function(){var a=i;if(w){a=new K(0,600);a.G($b)}return a},dc=cc(),ec="on",fc={},gc=function(a,b,c,d,e){if(b)if(s(b)=="array"){for(var f=0;f<b.length;f++)gc(a,b[f],c,d,e);return i}else{var h=!!d,j=P;b in j||(j[b]=Vb.k());j=j[b];if(!(h in j)){j[h]=Vb.k();j.p++}j=j[h];var k=ta(a),m,o;if(j[k]){m=j[k];for(var f=0;f<m.length;f++){o=m[f];if(o.listener==c&&o.handler==e){if(o.removed)break;return m[f].key}}}else{m=j[k]=Q.k();j.p++}var p=Wb.k();p.src=a;o=Zb.k();o.init(c,p,
a,b,h,e);var q=o.key;p.key=q;m.push(o);Tb[q]=o;Ub[k]||(Ub[k]=Q.k());Ub[k].push(o);if(a.addEventListener){if(a==r||!a.Mb)a.addEventListener(b,p,h)}else a.attachEvent(hc(b),p);return q}else throw Error("Invalid event type");},ic=function(a,b,c,d,e){if(s(b)=="array"){for(var f=0;f<b.length;f++)ic(a,b[f],c,d,e);return i}var h=!!d,j=jc(a,b,h);if(!j)return g;for(var f=0;f<j.length;f++)if(j[f].listener==c&&j[f].capture==h&&j[f].handler==e)return kc(j[f].key);return g},kc=function(a){if(!Tb[a])return g;var b=
Tb[a];if(b.removed)return g;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==r||!c.Mb)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(hc(d),e);var h=ta(c),j=P[d][f][h];if(Ub[h]){var k=Ub[h];ya(k,b);k.length==0&&delete Ub[h]}b.removed=l;j.Ba=l;lc(d,f,h,j);delete Tb[a];return l},lc=function(a,b,c,d){if(!d.P)if(d.Ba){for(var e=0,f=0;e<d.length;e++)if(d[e].removed)Zb.u(d[e]);else{if(e!=f)d[f]=d[e];f++}d.length=f;d.Ba=g;if(f==0){Q.u(d);delete P[a][b][c];P[a][b].p--;
if(P[a][b].p==0){Vb.u(P[a][b]);delete P[a][b];P[a].p--}if(P[a].p==0){Vb.u(P[a]);delete P[a]}}}},jc=function(a,b,c){var d=P;if(b in d){d=d[b];if(c in d){d=d[c];var e=ta(a);if(d[e])return d[e]}}return i},hc=function(a){if(a in fc)return fc[a];return fc[a]=ec+a},nc=function(a,b,c,d){var e=1,f=P;if(b in f){f=f[b];if(c in f){f=f[c];var h=ta(a);if(f[h]){var j=f[h];if(j.P)j.P++;else j.P=1;try{var k=j.length;for(var m=0;m<k;m++){var o=j[m];if(o&&!o.removed)e&=mc(o,d)!==g}}finally{j.P--;lc(b,c,h,j)}}}}return Boolean(e)},
mc=function(a,b){var c=a.handleEvent(b);a.ma&&kc(a.key);return c},Xb=function(a,b){if(!Tb[a])return l;var c=Tb[a],d=c.type,e=P;if(!(d in e))return l;e=e[d];var f;if(w){var h=b||la("window.event"),j=l in e;if(j){if(h.keyCode<0||h.returnValue!=undefined)return l;oc(h)}ta(c.src);var k=dc.k();k.init(h,this);f=l;try{if(j){var m=Q.k();for(var o=k.currentTarget;o;o=o.parentNode)m.push(o);for(var p=m.length-1;!k.F&&p>=0;p--){k.currentTarget=m[p];f&=nc(m[p],d,l,k)}for(var p=0;!k.F&&p<m.length;p++){k.currentTarget=
m[p];f&=nc(m[p],d,g,k)}}else f=mc(c,k)}finally{if(m){m.length=0;Q.u(m)}k.dispose();dc.u(k)}return f}var q=new M(b,this);try{f=mc(c,q)}finally{q.dispose()}return f},oc=function(a){var b=g;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=l}if(b||a.returnValue==undefined)a.returnValue=l};var R=function(a){this.a=a;this.Ob=this.a.c.pru;this.sb=this.a.c.ifrid;x&&pc()};u(R,G);if(x){var qc=[],rc=0,pc=function(){rc||(rc=window.setTimeout(function(){sc()},1000))},sc=function(a){var b=va(),c=a||3000;while(qc.length&&b-qc[0].timestamp>=c){var d=qc.shift().iframeElement;lb(d)}rc=window.setTimeout(tc,1000)},tc=function(){sc()}}R.prototype.f=3;R.prototype.connect=function(){this.send("tp","SETUP")};R.prototype.H=function(a){if(a=="SETUP"){this.send("tp",E);this.a.m()}else a==E&&this.a.m()};
R.prototype.send=function(a,b){if(w){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=uc}else{var d=document.createElement("iframe");x?qc.push({timestamp:va(),iframeElement:d}):gc(d,"load",uc)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.Ob;f+="#"+this.a.name;if(this.sb)f+=","+this.sb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d)};
var uc=function(){lb(this);this.xpcOnload=i};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);F[a].j(d,decodeURIComponent(e))};R.prototype.b=function(){R.o.b.call(this);x&&sc(0)};var S=function(a,b){this.a=a;this.aa=b||"*"};u(S,G);S.prototype.f=1;var vc=g,xc=function(){if(!vc){gc(window.postMessage?window:document,"message",wc,g,S);vc=l}},wc=function(a){var b=a.eb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return g;var e=b.substring(0,c),f=b.substring(c+1,d),h=b.substring(d+1),j=F[e];if(j){j.j(f,h);return l}for(var k in F){var m=F[k];if(m.r()==1&&!m.g()&&f=="tp"&&h=="SETUP"){m.name=e;F[e]=m;F[k]=i;m.j(f,h);return l}}return g};
S.prototype.H=function(a){switch(a){case "SETUP":if(!this.Sb){this.Sb=l;this.send("tp",E)}break;case E:this.a.m();break}};S.prototype.connect=function(){xc();this.U()};S.prototype.U=function(){if(!this.a.g()){this.send("tp","SETUP");window.setTimeout(t(this.U,this),100)}};S.prototype.send=function(a,b){var c=this.a.h;if(!!c){var d=c.postMessage?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,this.aa)};this.send(a,b)}};
S.prototype.b=function(){S.o.b.call(this);ic(window.postMessage?window:document,"message",wc,g,S)};var T=function(a){this.a=a;this.Na=a.at||"";this.yb=a.rat||"";yc();this[zc]=this.N;this[Ac]=this.Ua};u(T,G);
var Bc="GCXPC____NIXVBS_wrapper",Cc="GCXPC____NIXVBS_get_wrapper",zc="GCXPC____NIXJS_handle_message",Ac="GCXPC____NIXJS_create_channel",Dc="GCXPC____NIXVBS_container",yc=function(){if(!window.nix_setup_complete){var a="Class "+Bc+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+zc+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Ac+"(channel)\nEnd Sub\nPublic Sub "+Dc+"()\n End Sub\nEnd Class\n Function "+Cc+"(transport, auth)\nDim wrap\nSet wrap = New "+Bc+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Cc+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=l}catch(b){}}};T.prototype.f=6;T.prototype.t=g;T.prototype.n=i;T.prototype.connect=function(){this.a.r()==0?this.ka():this.ja()};
T.prototype.ka=function(){if(!this.t){var a=this.a.s;try{a.contentWindow.opener=window[Cc](this,this.Na);this.t=l}catch(b){}this.t||window.setTimeout(t(this.ka,this),100)}};T.prototype.ja=function(){if(!this.t){try{var a=window.opener;if(a&&Dc in a){this.n=a;var b=this.n.GetAuthToken();if(b!=this.yb)return;this.n.CreateChannel(window[Cc](this,this.Na));this.t=l;this.a.m()}}catch(c){return}this.t||window.setTimeout(t(this.ja,this),100)}};
T.prototype.Ua=function(a){this.n=a;var b=this.n.GetAuthToken();b!=this.yb||this.a.m()};T.prototype.N=function(a,b){function c(){this.a.j(a,b)}window.setTimeout(t(c,this),1)};T.prototype.send=function(a,b){this.n.SendMessage(a,b)};T.prototype.b=function(){T.o.b.call(this);this.n=i};var U=function(a){C.call(this);this.c=a;this.name=this.c.cn||Ib(10);this.Ia={};F[this.name]=this;gc(window,"unload",Ec)};u(U,C);U.prototype.d=i;U.prototype.ga=1;U.prototype.g=function(){return this.ga==2};U.prototype.h=i;U.prototype.s=i;U.prototype.Ka=function(a){this.h=a};
U.prototype.Wa=function(){if(!this.d){if(!this.c.tp)if(pa(document.postMessage)||pa(window.postMessage)||w&&window.postMessage)this.c.tp=1;else if(Qa)this.c.tp=2;else if(w&&this.c.pru)this.c.tp=3;else if(w)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.d=new S(this,this.c.ph);break;case 6:this.d=new T(this);break;case 2:this.d=new H(this);break;case 3:this.d=new R(this);break;case 4:this.d=new I(this);break}if(!this.d)throw Error("CrossPageChannel: No suitable transport found!");
}};U.prototype.Ya=g;U.prototype.Ra=g;U.prototype.connect=function(a){this.Lb=a;if(this.Ya)this.Ra=l;else{if(this.c.ifrid)this.s=typeof this.c.ifrid=="string"?document.getElementById(this.c.ifrid):this.c.ifrid;if(this.s){var b=this.s.contentWindow;b||(b=window.frames[this.c.ifrid]);this.Ka(b)}if(!this.h)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.Ka(window.parent);this.Wa();this.d.connect()}};
U.prototype.close=function(){if(!!this.g()){this.ga=3;this.d.dispose();this.d=i}};U.prototype.m=function(){if(!this.g()){this.ga=2;this.Lb()}};U.prototype.qb=function(){this.close()};U.prototype.xb=function(a,b,c){this.Ia[a]={name:a,callback:b,jsonEncoded:!!c}};U.prototype.send=function(a,b){if(!!this.g())if(this.h.closed)this.close();else{if(qa(b))b=(new D).serialize(b);this.d.send(a,b)}};
U.prototype.j=function(a,b){if(!a||a=="tp")this.d.H(b);else if(this.g()){var c=this.Ia[a];if(c){if(c.jsonEncoded)try{b=Eb(b)}catch(d){return}c.callback(b)}}};U.prototype.r=function(){return window.parent==this.h?1:0};U.prototype.b=function(){U.o.b.call(this);this.close();this.s=this.h=i;delete this.Ia;F[this.name]=i};var Ec=function(){for(var a in F){var b=F[a];b&&b.dispose()}};var Fc=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/robots.txt"};var V=function(a,b){this.A=a.width;this.z=a.height;this.Kb=b;this.aa=this.fb(a.src,document);this.Z=g;this.e=a;this.lb(this.hb())};V.prototype.hb=function(){var a={};a.ifrid=this.e.id;a.pu=this.e.src;a.ph=this.aa;a.cn=this.Kb;a.ppu=Fc(this.aa);a.lpu=Fc();return a};V.prototype.lb=function(a){this.a=new U(a);this.a.xb("expandable_ad",t(this.N,this));this.a.connect(function(){});window.setTimeout(t(this.jb,this),30000)};
V.prototype.jb=function(){if(this.a&&!this.a.g()){this.a.d.connect=function(){};if(this.a.d.f==1)this.a.d.U=function(){};if(this.a.d.f==4)this.a.d.Tb=function(){};this.a.d.dispose();this.a.dispose()}};V.prototype.fb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,h=f.indexOf("/");if(h<0)h=f.indexOf("?");if(d&&h>0)f=f.substring(0,h);return e+"//"+f};
V.prototype.N=function(a){var b=a.split("_"),c=b[0];if(c=="expand")this.kb(b);else c=="collapse"&&this.ib()};V.prototype.Fa=function(a){this.a.send("expandable_ad",a)};V.prototype.kb=function(a){if(!this.Z){var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.$a(b,c);this.bb(b,c,f);this.Fa("ok_expand_w"+b+"_h"+c+"_d"+f)}};
V.prototype.ib=function(){if(!!this.Z){this.Qa();this.Fa("ok_collapse_w"+this.A+"_h"+this.z)}};V.prototype.Qa=function(){this.e.style.width=this.A+"px";this.e.style.height=this.z+"px";this.e.style.left="0";this.e.style.top="0";this.e.style.zIndex=i;this.e.parentNode.style.zIndex=i;this.e.parentNode.parentNode.style.zIndex=i;this.Z=g};
V.prototype.bb=function(a,b,c){this.e.style.position="absolute";this.e.style.width=a+"px";this.e.style.height=b+"px";this.e.style.zIndex=9999;this.e.parentNode.style.zIndex=9999;this.e.parentNode.parentNode.style.zIndex=9999;if(a>this.A&&(c==0||c==3))this.e.style.left="-"+(a-this.A)+"px";if(b>this.z&&(c==1||c==0))this.e.style.top="-"+(b-this.z)+"px";this.Z=l};
V.prototype.$a=function(a,b){var c=vb(this.e),d=jb(window),e=a-this.A,f=b-this.z,h=c.y,j=f>h,k=d.height-(c.y+this.z),m=j||k>=h,o=c.x,p=e>o,q=d.width-(c.x+this.A),J=p||q>=o,N=0;if(m&&J)N=2;else if(m&&!J)N=3;else if(!m&&J)N=1;else if(!m&&!J)N=0;return N};
var Gc=function(){},Jc=function(a,b,c,d,e){if(!a||!b||c<=0||d<=0)return i;var f=Ib(10);b=Hc(b,c,d,f);var h=Ic(a,b,c,d,e);return new V(h,f)},Hc=function(a,b,c,d){var e=cb().va();return a+(a.indexOf("?")==-1?"?":"&")+"w="+b+"&h="+c+"&xpc="+d+"&p="+escape(e.location.protocol+"//"+e.location.host)},Ic=function(a,b,c,d,e){var f="border:none;height:"+d+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+c+"px",h='<ins style="display:inline-table;'+f+'"><ins style="display:block;'+f+'"><iframe allowtransparency=true frameborder=0 height='+
d+" hspace=0 id="+a+' marginheight=0 marginwidth=0 name=google_ads_frame scrolling=no src="'+b+'" style="left:0;position:absolute;top:0" vspace=0 width='+c+"></iframe></ins></ins>",j=cb(),k=j.xa(e);if(k)k.innerHTML=h;else j.va().write(h);return j.xa(a)};wa("ExpandableAdSlot",V);wa("ExpandableAdSlotFactory",Gc);var W="";function Kc(a){if(a){if(W!="")W+=",";W+=a}}var Lc=g,Mc=fa("false",g);function Nc(a){return a!=i?'"'+a+'"':'""'}function da(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function X(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function Y(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];X(c,d)}function Z(a,b){b!=i&&X(a,da(b))}function $(a){var b=window,c=ba[a]||ca[a]||i,d=b[a];Z(c,d)}
function Oc(a,b){var c=window,d=ba[a]||ca[a]||i,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];X(d,e)}function Pc(a){var b=a.screen,c=navigator.javaEnabled(),d=-(new Date).getTimezoneOffset();if(b){X("u_h",b.height);X("u_w",b.width);X("u_ah",b.availHeight);X("u_aw",b.availWidth);X("u_cd",b.colorDepth)}X("u_tz",d);X("u_his",history.length);X("u_java",c);navigator.plugins&&X("u_nplug",navigator.plugins.length);navigator.mimeTypes&&X("u_nmime",navigator.mimeTypes.length)}
function Qc(a){if(!!a.google_enable_first_party_cookie){if(a._GA_googleCookieHelper==i)a._GA_googleCookieHelper=new n;if(!a._google_cookie_fetched){a._google_cookie_fetched=l;a._GA_googleCookieHelper.cb(Rc(a.google_ad_client))}}}function Rc(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function Sc(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}function Tc(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}
function Uc(){var a=w&&y("6")&&!y("8"),b=Qa&&y("1.8.1"),c=x&&y("525");if(Xa&&(a||b||c))return l;else if(Wa&&(c||b))return l;else if(Ya&&b)return l;return g}function Vc(a,b){var c=a.google_allow_expandable_ads;if(c!=i&&c==g||!b.body||a.google_ad_output!="html"||Wc(a,b)||Xc(a)||Yc(a.google_ad_format)||isNaN(a.google_ad_height)||isNaN(a.google_ad_width)||!Uc())return g;return l}
function Zc(){var a=Math.random(),b=ea("0.03",0.03),c=2*b;if(a<b)return"30143019";if(a<c)return"30143020";return""}function $c(){var a=Math.random(),b=ea("0.03",0.03),c=2*b;if(a<b)return"30143021";if(a<c)return"30143022";return""}function ad(){var a=Math.random(),b=ea("0.02",0.01),c=2*b;if(a<b)return"6083029";if(a<c)return"6083028";return""}function bd(a){a.google_allow_expandable_ads=g;a.google_expandable_iframe=g}
var cd=Math.random()<0.0010;function dd(a,b){a.google_image_requests||(a.google_image_requests=[]);var c=new Image;c.src=b;a.google_image_requests.push(c)}
function ed(a,b,c,d){var e=Tc(a);c=c.substring(0,1992);c=c.replace(/%\w?$/,"");var f="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+f+' language="JavaScript1.1" src='+Nc(fd(c))+"></"+f+">");else if(a.google_ad_output=="html")if(gd(a)){var h=a.google_container_id||d||i;a["google_expandable_ad_slot"+e]=Jc("google_ads_frame"+e,fd(c),a.google_ad_width,a.google_ad_height,h)}else{var j='<iframe name="google_ads_frame" width='+
Nc(a.google_ad_width)+" height="+Nc(a.google_ad_height)+" frameborder="+Nc(a.google_ad_frameborder)+" src="+Nc(fd(c))+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';j=hd(a.google_ad_width,a.google_ad_height,j);a.google_container_id?id(a.google_container_id,b,j):b.write(j)}else a.google_ad_output=="textlink"&&b.write("<"+f+' language="JavaScript1.1" src='+Nc(fd(c))+"></"+f+">");if(cd){var k=jd(a)+"/pagead/gen_204?id=ifjs2&token="+a.google_correlator+
"&output="+da(a.google_ad_output)+"&url="+da(a.google_page_url);dd(a,k)}}function gd(a){if(!Lc)return g;var b=W.indexOf("30143020")!=-1,c=W.indexOf("30143019")!=-1,d=a.google_expandable_iframe;return Mc&&!c||b||d}function kd(a){var b=fa("false",g);return b&&a.indexOf("30143021")==-1||a.indexOf("30143022")!=-1}
function hd(a,b,c){var d=kd(W);if(Lc&&d){var e="border:none;height:"+b+"px;margin:0;padding:0;position:relative;visibility:visible;width:"+a+"px";return'<ins style="display:inline-table;'+e+'"><ins style="display:block;'+e+'">'+c+"</ins></ins>"}return c}function ld(a){for(var b in ba)a[b]=i;for(var b in ca)b=="google_correlator"||(a[b]=i);a.google_allow_expandable_ads=i;a.google_container_id=i;a.google_expandable_iframe=i;a.google_tag_js_version=i}
function Xc(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Yc(a){return a&&a.indexOf("_sdo")!=-1}
function md(a){var b=i,c=window,d=document,e=aa,f=c.google_ad_format,h=jd(c),j;if(c.google_cpa_choice!=b){c.google_ad_url=h+"/cpa/ads?";j=escape(Rc(c.google_ad_client));c.google_ad_region="_google_cpa_region_";Y("google_cpa_choice");if(typeof d.characterSet!="undefined")Z("oe",d.characterSet);else typeof d.charset!="undefined"&&Z("oe",d.charset)}else if(Yc(f)){c.google_ad_url=h+"/pagead/sdo?";j=escape(Sc(c.google_ad_client))}else{c.google_ad_url=h+"/pagead/ads?";j=escape(Rc(c.google_ad_client))}c.google_ad_url+=
"client="+j;Y("google_ad_host");Y("google_ad_host_tier_id");var k=c.google_num_slots_by_client,m=c.google_num_slots_by_channel,o=c.google_prev_ad_formats_by_region,p=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var q=c.google_ad_region==b?"":c.google_ad_region;if(Yc(f)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>4)return g}else if(Xc(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?
c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return g}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){o[q]=b;p[q]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=e%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return g}else if(c.google_num_ad_slots>6&&q=="")return g}X("dt",aa);Y("google_language");c.google_country?Y("google_country"):Y("google_gl");Y("google_region");
$("google_city");$("google_hints");Y("google_safe");Y("google_encoding");Y("google_last_modified_time");$("google_alternate_ad_url");Y("google_alternate_color");Y("google_skip");Y("google_targeting");var J=c.google_ad_client;if(k[J])k[J]+=1;else{k[J]=1;k.length+=1}if(o[q])if(!Yc(f)){Z("prev_fmts",o[q].toLowerCase());k.length>1&&X("slot",k[J])}p[q]&&Z("prev_slotnames",p[q].toLowerCase());if(f&&!c.google_ad_slot){Z("format",f.toLowerCase());Yc(f)||(o[q]=o[q]?o[q]+","+f:f)}if(c.google_ad_slot)p[q]=p[q]?
p[q]+","+c.google_ad_slot:c.google_ad_slot;Y("google_max_num_ads");X("output",c.google_ad_output);Y("google_adtest");Y("google_ad_callback");Y("google_ad_slot");$("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&X("dblk",1);if(c.google_ad_channel){$("google_ad_channel");var N="",ac=c.google_ad_channel.split(nd);for(var eb=0;eb<ac.length;eb++){var fb=ac[eb];if(m[fb])N+=fb+"+";else m[fb]=1}Z("pv_ch",N)}if(c.google_ad_host_channel){$("google_ad_host_channel");var vd=
od(c.google_ad_host_channel,c.google_viewed_host_channels);Z("pv_h_ch",vd)}c.google_enable_first_party_cookie&&Z("cookie",c._GA_googleCookieHelper.gb());$("google_page_url");Oc("google_color_bg",e);Oc("google_color_text",e);Oc("google_color_link",e);Oc("google_color_url",e);Oc("google_color_border",e);Oc("google_color_line",e);c.google_reuse_colors?X("reuse_colors",1):X("reuse_colors",0);Y("google_kw_type");$("google_kw");$("google_contents");Y("google_num_radlinks");Y("google_max_radlink_len");Y("google_rl_filtering");
Y("google_rl_mode");Y("google_rt");$("google_rl_dest_url");Y("google_num_radlinks_per_unit");Y("google_ad_type");Y("google_image_size");Y("google_ad_region");Lc=Vc(c,d);if(!Lc)bd(c);else if(c.google_expandable_iframe===g)bd(c);else if(j in{"ca-pub-2944451727872625":1,"ca-pub-9483266128490610":1,"ca-pub-1955924717845427":1,"ca-pub-6664249124335298":1})c.google_expandable_iframe=l;else if(!(c.google_expandable_iframe==l)){var na=Zc();Kc(na);if(na=="30143019"||na==""&&!Mc)bd(c);if(!na){na=$c();Kc(na)}}X("eid",
W);var bc=c.google_allow_expandable_ads;if(bc!=i)bc?X("ea","1"):X("ea","0");Y("google_feedback");$("google_referrer_url");$("google_page_location");X("frm",c.google_iframing);Y("google_bid");Y("google_ctr_threshold");Y("google_cust_age");Y("google_cust_gender");Y("google_cust_interests");Y("google_cust_id");Y("google_cust_job");Y("google_cust_u_url");Y("google_cust_l");Y("google_cust_lh");Y("google_cust_ch");Y("google_ed");Y("google_video_doc_id");Y("google_video_product_type");$("google_ui_features");
$("google_ui_version");$("google_tag_js_version");$("google_only_ads_with_video");$("google_disable_video_autoplay");if(a){Z("ff",wb(a));var gb=ub(a),hb=jb();if(gb&&hb){Z("biw",hb.width);Z("bih",hb.height);Z("adx",gb.x);Z("ady",gb.y)}}yb();X("ga_vid",c.gaGlobal.vid);X("ga_sid",c.gaGlobal.sid);X("ga_hid",c.gaGlobal.hid);X("ga_fc",c.gaGlobal.from_cookie);$("google_analytics_uacct");Y("google_ad_override");Y("google_flash_version");Pc(c);cd&&X("gen_204","ifjs2");return l}
function od(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var h=c[f].split(nd);b[f]||(b[f]={});var j="";for(var k=0;k<h.length;k++){var m=h[k];if(!(m==""))if(b[f][m])j+="+"+m;else b[f][m]=1}j=j.slice(1);e[f]=j;if(j!="")d=f}var o="";if(d>-1){for(var f=0;f<d;f++)o+=e[f]+"|";o+=e[d]}return o}
function pd(){var a=window,b=document;Qc(a);var c=ad();Kc(c);var d;if(c=="6083029"){var e="google_temp_span";d=a.google_container_id&&ib(a.google_container_id)||ib(e);if(!d&&!a.google_container_id){b.write("<span id="+e+"></span>");d=ib(e)}}var f=md(d);d&&d.id==e&&lb(d);if(!!f){ed(a,b,a.google_ad_url);ld(a)}}function fd(a){var b=(new Date).getTime()-aa,c="&dtd="+(b<1000?b:"M");return a+c}function qd(){pd();return l}
function Wc(a,b){if(a.top.location==b.location)return g;var c=b.documentElement;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return g}return l}
function rd(a){var b=window,c=i,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Yc(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;sd(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=aa;if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot={};if(b.google_flash_version==
c)b.google_flash_version=ga();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function td(a){if(a in ud)return ud[a];return ud[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var ud={};function ha(){return td("msie")&&!window.opera}
function wd(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(h){}}return b}function xd(){var a=window,b=wd(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function yd(a,b){for(var c in b)a["google_"+c]=b[c]}
function zd(a,b){if(!b)return a.location;return a.referrer}function Ad(a,b){if(!b&&a.google_referrer_url==i)return"0";else if(b&&a.google_referrer_url==i)return"1";else if(!b&&a.google_referrer_url!=i)return"2";else if(b&&a.google_referrer_url!=i)return"3";return"4"}function Bd(a,b,c,d){a.page_url=zd(c,d);a.page_location=i}function Cd(a,b,c,d){a.page_url=b.google_page_url;a.page_location=zd(c,d)||"EMPTY"}
function Dd(a,b){var c={},d=Wc(a,b);c.iframing=Ad(a,d);!!a.google_page_url?Cd(c,a,b,d):Bd(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:i;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function Ed(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=i;b.page_url=c;b.page_location=a.location;b.last_modified_time=i;b.referrer_url=c;return b}
function sd(a,b){var c;c=a.google_page_url==i&&Fd[b.domain]?Ed(b):Dd(a,b);yd(a,c)}function id(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}var Fd={};Fd["ad.yieldmanager.com"]=l;var nd=/[+, ]/;window.google_render_ad=pd;var Gd={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};function Hd(a){var b=a.google_page_location||a.google_page_url;if(!b)return g;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=g;if(e.length>=3)f=e[e.length-3]in Gd;if(e.length>=2)f=f||e[e.length-2]in Gd;return f}
function Id(a,b,c){if(Hd(a)){a.google_new_domain_checked=1;return g}if(a.google_new_domain_checked==0){var d=Math.random();if(d<=c){var e="http://googleads.g.doubleclick.net/pagead/test_domain.js",f="script";b.write("<"+f+' src="'+e+'"></'+f+">");a.google_new_domain_checked=1;return l}}return g}function jd(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!Hd(a)&&a.google_new_domain_enabled==1)return b;return c};function Jd(a,b){var c="script",d=Id(a,b,ea("1",0.01));d&&ha()?b.write("<"+c+' src="http://pagead2.googlesyndication.com/pagead/render_ads.js"></'+c+">"):b.write("<"+c+">window.google_render_ad();</"+c+">")}xd();rd(qd);Jd(window,document);
})()
